### PR TITLE
Add missing include files (based on MSVC errors).

### PR DESCRIPTION
**Pull request by bjones1**
I'm working to get libcoro and test building with MSVC. Here's some fixes that allow me to make progress.

I'll keep this as a draft until tests pass, then move to a regular PR. In the draft mode, I'll force-push fixes to leave a clean commit history for the final PR. Let me know if you prefer some other flow.

### CODE REVIEW

**Comment by bjones1** [comment]
It looks like CI is blocked until you approve. Would you approve, or do you want some other process?

Thanks!

**Comment by jbaldwin** [comment]
Apologies on the delay, been out of town.  It seems like this PR should include a new ci pipeline for compiling with MSVC?

**Comment by bjones1** [comment]
> Apologies on the delay, been out of town. 

No worries!

> It seems like this PR should include a new ci pipeline for compiling with MSVC?

Yes, but let me postpone that for another PR (unless you'd like a large PR). There are more fixes required before it compiles with MSVC.

**Comment by bjones1** [comment]
I'm moving this to a full PR for now, since tests (in their current state) pass.

**Comment by jbaldwin** [comment]
Yeah we can add it as another PR. I can merge this one now since it passed.

**Review by jbaldwin — APPROVED** [review]

**Pull request merged**
