### PR TITLE
Better MSVC support

### PR DESCRIPTION
**Pull request by bjones1**
This adds warning flags for MSVC and cleans up minor complains when it's passed GCC-only flags.

### CODE REVIEW

**Comment by jbaldwin** [comment]
Since you are now starting to add specific MSVC flags to the cmake files can you add a GitHub action that compiles with MSVC and runs the tests please?

**Comment by bjones1** [comment]
I'd be happy to. However, tests will fail until this and the other PRs are merged. Is that OK?

**Comment by bjones1** [comment]
> Since you are now starting to add specific MSVC flags to the cmake files can you add a GitHub action that compiles with MSVC and runs the tests please?

I went ahead and created #188.

**Comment by jbaldwin** [comment]
Cool #188 works, we can work towards getting that to pass with each PR.

**Review by jbaldwin — DISMISSED** [review]

**Comment by bjones1** [comment]
Fantastic!

**Comment by jbaldwin** [comment]
Sorry, looks like this has a conflict now with the other two PRs that just merged, would you mind resolving them?

**Comment by bjones1** [comment]
No problem, done!

**Review by jbaldwin — APPROVED** [review]

**Pull request merged**
